Layout/LineLength:
  Max: 120

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: compact
