version: "3"
services:
  dev:
    image: ruby-with-chrome:2.6
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - bundler-cache:/usr/local/bundle
    working_dir: /usr/src/app

volumes:
  bundler-cache:
    driver: local
