version: "3"
services:
  chrome:
    tty: true
    stdin_open: true
    build: .
    environment:
      BUNDLE_PATH: /usr/local/bundle
      DEBUG: 1
      CI: 1
    volumes:
      - .:/puppeteer-ruby
      - bundle-data:/usr/local/bundle
    working_dir: /puppeteer-ruby
    command: bundle exec rspec

  firefox:
    tty: true
    stdin_open: true
    build: .
    environment:
      BUNDLE_PATH: /usr/local/bundle
      PUPPETEER_PRODUCT_RSPEC: firefox
      DEBUG: 1
      CI: 1
    volumes:
      - .:/puppeteer-ruby
      - bundle-data:/usr/local/bundle
    working_dir: /puppeteer-ruby
    command: bundle exec rspec spec/integration/

volumes:
  bundle-data:
    driver: local
