version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.6.6-buster-node-browsers
    executor: ruby/default
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          name: rspec
          command: |
            DEBUG=1 bundle exec rspec --profile 10 \
              --format RspecJunitFormatter \
              --out test_results/rspec.xml \
              --format documentation

  rspec_firefox:
    docker:
      - image: circleci/ruby:2.6.6-buster-node-browsers
    executor: ruby/default
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          name: install firefox-nightly
          command: |
            wget -O nightly.tar.bz2 "https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=linux64&lang=en-US"
            tar xf nightly.tar.bz2
      - run:
          name: rspec
          command: |
            DEBUG=1 PUPPETEER_PRODUCT=firefox \
            PUPPETEER_EXECUTABLE_PATH=${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/firefox/firefox \
            bundle exec rspec --profile 10 \
              --format RspecJunitFormatter \
              --out test_results/rspec.xml \
              --format documentation spec/integration/

  deploy:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: rake build
          command: rake build
      - run:
          name: setup API key
          command: |
            mkdir -p ~/.gem/
            echo "---" > ~/.gem/credentials
            echo ":rubygems_api_key: $RUBYGEMS_API_KEY" >> ~/.gem/credentials
            chmod 600 ~/.gem/credentials
      - run:
          name: Check Puppeteer::version
          command: bundle exec ruby -e 'raise "invalid Puppeteer::VERSION" unless Puppeteer::VERSION == ENV["CIRCLE_TAG"]'
      - run:
          name: gem push
          command: gem push pkg/puppeteer-ruby-$CIRCLE_TAG.gem

workflows:
  ci:
    jobs:
      - rspec
      - rspec_firefox
  rubygems-deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^[0-9]\.[0-9]+\.[0-9].*/
            branches:
              ignore: /.*/
